# Generated by Django 5.1.1 on 2024-10-16 09:54

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('restaurant_type', models.BooleanField(default=False)),
                ('location', models.TextField(null=True)),
                ('rating', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Food Description embeddings', null=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.restaurant')),
            ],
        ),
    ]
