# Generated by Django 5.1.1 on 2024-10-16 13:36

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AddIndex(
            model_name='food',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='food_desc_vector_index', opclasses=['vector_cosine_ops']),
        ),
    ]
