# Generated by Django 5.1.1 on 2024-10-06 11:25

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChatBot', '0001_extension001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('restaurent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('restaurent_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Food Description embeddings', null=True)),
                ('restaurent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.restaurent')),
            ],
        ),
    ]
