# Generated by Django 5.1.1 on 2024-10-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurent',
            new_name='Restaurant',
        ),
    ]
