# Generated by Django 5.1.1 on 2024-10-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0003_rename_restaurent_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurent_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurent_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurent_type',
            new_name='restaurant_type',
        ),
    ]
