# Generated by Django 5.1.1 on 2024-10-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
