# Generated by Django 5.1.1 on 2024-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0006_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.SmallIntegerField(default=1, max_length=5),
        ),
    ]
