# Generated by Django 5.1.1 on 2024-10-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0008_food_food_desc_vector_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
